# Generated by Django 3.1.3 on 2020-11-24 15:57

from django.db import migrations


def add_root_page(apps, schema_editor):
    Page = apps.get_model('tree', 'Page')
    Page.objects.create(
        name='root',
        text='root page'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_root_page)
    ]
